name: Handle imported files

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Execute Python
        run: |
          python handle_imports.py
      - name: Commit changes
        run: |
          git config --global user.email "email"
          git config --global user.name "Actions Bot"
          git add .
          git commit -m "Handle imported files from Math-Notes"
          git push